language: php
sudo: true
php:
- 5.6

cache:
  bundler: true
  apt: true#
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"

matrix:
  fast_finish: true
env:
  global:
  - PATH="$PATH:$HOME/.composer/vendor/bin"
  - DRUPAL_TI_MODULE_NAME="scheduler"
  - DRUPAL_TI_SIMPLETEST_GROUP="Scheduler"
  - DRUPAL_TI_ENVIRONMENT="drupal-8"
  - DRUPAL_TI_DB="drupal_travis_db"
  - DRUPAL_TI_DB_URL="mysql://root:@127.0.0.1/drupal_travis_db"
  - DRUPAL_TI_WEBSERVER_URL="http://127.0.0.1"
  - DRUPAL_TI_WEBSERVER_PORT="8080"
  - DRUPAL_TI_SIMPLETEST_ARGS="--verbose --color --concurrency 4 --url $DRUPAL_TI_WEBSERVER_URL:$DRUPAL_TI_WEBSERVER_PORT"
  - DRUPAL_TI_BEHAT_DIR="./tests/behat"
  - DRUPAL_TI_BEHAT_ARGS=""
  - DRUPAL_TI_BEHAT_YML="behat.yml.dist"
  - DRUPAL_TI_BEHAT_SCREENSIZE_COLOR="1280x1024x16"
  - DRUPAL_TI_BEHAT_SELENIUM_VERSION="2.48.2"
  - DRUPAL_TI_BEHAT_DRIVER="phantomjs"
  - DRUPAL_TI_BEHAT_BROWSER="firefox"
  - DRUPAL_TI_PHPUNIT_ARGS=""
  - DRUPAL_TI_COVERAGE="satooshi/php-coveralls:0.6.*"
  - DRUPAL_TI_COVERAGE_FILE="build/logs/clover.xml"
  - DRUPAL_TI_SIMPLETEST_COVERAGE="1"
  - DRUPAL_TI_SIMPLETEST_COVERAGE_GENERATE_BADGES="1"
  - DRUPAL_TI_GITHUB_EMAIL="legovaer@me.com"
  - DRUPAL_TI_GITHUB_NAME="Levi Govaerts"
  - secure: "i5NiF0cXuYu+Ykd25U0u9kX1OUJJbVNyRp+nCVF86oMv20b0UlTN41Z1pnDOxtPlIZK7+F64gg/bW6CldP58CH3UABiN3LaqSzeip2FxiACeYwsDmuVkbAQ5P+uZbdhc9O8/8KN4CRnACJP5xA/dsLIowmeecsBrUVgGCfFpQbpSJvCw3kQ2qezHoomFytIb8D4/LnRH0jUJkniUmgj0hvRb8O5UibbKrVwIjQnHCeLL6isaGCzWfcYejQgJXV04DsEfuOAh2iATQSyCce/yNYTyya8pbzTnSAQSF8VDmQOjXdYVFRJzxhthOCsTnQbgZGiHhFG9lul819v8k24JpOFVnn8I5f9Ki0r1eM+AvB838MCEQn8Qn5IjIWaCVe0IS5Fz22WB9j6YqJUdEze4AVlXdiDOIhENc8KDjlYbZbsUDJarL/1AksDUoSKWUiEMI6uW0CCUCoxTw5HUVkHScHNVKyrPCEW5+6OBF/eZChuTHqAJY2iD6NxsYjkcgT4ZYg4k+J3OcnVeup0q/8NrDequA0Js1kqX1YlgbO0ynQb/PLOG4rA7D8viz38FRQaSw8jNP5JNiNfz2DMnuNUFa77AKQ3KzPdMRX0FJoyRZCY+kOZ9GqAhVJVvYabQdcpsVJypUwGSOQXNix6v24hu2fFKIJtvtmCHjhqWOJitF5M="

  matrix:
  - DRUPAL_TI_RUNNERS="simpletest"
mysql:
  database: drupal_travis_db
  username: root
  encoding: utf8
before_install:
- composer self-update
# Installing drupal_ti manually as my pull request hasn't been merged yet.
- mkdir -p "$HOME/.composer/vendor/bin"
- cd $HOME
- git clone --branch travis-add-coverage-support https://github.com/legovaer/drupal_ti
- cd drupal_ti/
- composer install
- ln -sf $HOME/drupal_ti/drupal-ti "$HOME/.composer/vendor/bin"
- git clone --branch 7.x-1.x https://git.drupal.org/project/$DRUPAL_TI_MODULE_NAME.git $TRAVIS_BUILD_DIR/$DRUPAL_TI_MODULE_NAME
- drupal-ti before_install
install:
- drupal-ti install
before_script:
- drupal-ti before_script
script:
- drupal-ti script
after_script:
- drupal-ti after_script
notifications:
  email: false
