language: php
sudo: required
php:
- 5.6

services:
- docker

cache:
  bundler: true
  apt: true#
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"

matrix:
  fast_finish: true
env:
  global:
  - PATH="$PATH:$HOME/.composer/vendor/bin"
  - DRUPAL_TI_MODULE_NAME="scheduler"
  - DRUPAL_TI_SIMPLETEST_GROUP="Scheduler"
  - DRUPAL_TI_ENVIRONMENT="drupal-8"
  - DRUPAL_TI_DB="drupal_travis_db"
  - DRUPAL_TI_DB_URL="mysql://root:@127.0.0.1/drupal_travis_db"
  - DRUPAL_TI_WEBSERVER_URL="http://127.0.0.1"
  - DRUPAL_TI_WEBSERVER_PORT="8080"
  - DRUPAL_TI_SIMPLETEST_ARGS="--verbose --color --concurrency 4 --url $DRUPAL_TI_WEBSERVER_URL:$DRUPAL_TI_WEBSERVER_PORT"
  - DRUPAL_TI_BEHAT_DIR="./tests/behat"
  - DRUPAL_TI_BEHAT_ARGS=""
  - DRUPAL_TI_BEHAT_YML="behat.yml.dist"
  - DRUPAL_TI_BEHAT_SCREENSIZE_COLOR="1280x1024x16"
  - DRUPAL_TI_BEHAT_SELENIUM_VERSION="2.48.2"
  - DRUPAL_TI_BEHAT_DRIVER="phantomjs"
  - DRUPAL_TI_BEHAT_BROWSER="firefox"
  - DRUPAL_TI_PHPUNIT_ARGS=""
  - DRUPAL_TI_COVERAGE="satooshi/php-coveralls:0.6.*"
  - DRUPAL_TI_COVERAGE_FILE="build/logs/clover.xml"
  - DRUPAL_TI_SIMPLETEST_COVERAGE="0"
  - DRUPAL_TI_SIMPLETEST_COVERAGE_GENERATE_BADGES="1"
  - DRUPAL_TI_GITHUB_EMAIL="legovaer@me.com"
  - DRUPAL_TI_GITHUB_NAME="Levi Govaerts"
  - ENCRYPTION_LABEL="4bbb05651be3"
  - COMMIT_AUTHOR_EMAIL="legovaer@me.com"
  - DCI_CheckoutDir=$HOME/checkout
  - DCI_RunScript=/var/www/html/core/scripts/run-tests.sh
  - DCI_PHPVersion=5.6
  - DCI_JobType=simpletest
  - DCI_ComposerInstall=True
  - DCI_CoreBranch=8.3.x
  - DCI_Patch=add_readme_file-2809329-5.patch,modules/drupal_coverage_core
  - DCI_AdditionalRepositories=git,git://git.drupal.org/project/drupal_coverage_core.git,8.x-1.x,modules/drupal_coverage_core,1;
  - DCI_Color=True
  - DCI_JunitXml=xml
  - DCI_Fetch=https://www.drupal.org/files/issues/add_readme_file-2809329-5.patch,modules/drupal_coverage_core
  - DCI_TestItem=directory:modules/drupal_coverage_core
  - DCI_Concurrency=31
  - DCI_CoreRepository=git://git.drupal.org/project/drupal.git
  - DCI_DBVersion=mysql-5.5

  matrix:
  - DRUPAL_TI_RUNNERS="simpletest"
mysql:
  database: drupal_travis_db
  username: root
  encoding: utf8
before_install:
  - sudo sh -c 'echo "deb https://apt.dockerproject.org/repo ubuntu-precise main" > /etc/apt/sources.list.d/docker.list'
  - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  - sudo apt-get update
  - sudo apt-key update
  - sudo apt-get -qqy -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install docker-engine=1.11.1-0~precise
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.7.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose -v
  - docker -v
  - composer self-update
  # Installing drupal_ti manually as my pull request hasn't been merged yet.
  - mkdir -p "$HOME/.composer/vendor/bin"
  - cd $HOME
  - git clone --branch travis-add-coverage-support https://github.com/legovaer/drupal_ti
  - cd drupal_ti/
  - composer install
  - ln -sf $HOME/drupal_ti/drupal-ti "$HOME/.composer/vendor/bin"
  - cd $HOME
  - git clone --branch production https://git.drupal.org/project/drupalci_testbot.git
  - cd drupalci_testbot
  - composer install
  - ln -sf $HOME/drupalci_testbot/drupalci "$HOME/.composer/vendor/bin"
  - drupalci docker-rm containers
  - #git clone --branch 8.x-1.x https://git.drupal.org/project/$DRUPAL_TI_MODULE_NAME.git $TRAVIS_BUILD_DIR/$DRUPAL_TI_MODULE_NAME
  - #drupal-ti before_install
install:
#- drupal-ti install
before_script:
#- drupal-ti before_script
script:
  - drupalci run simpletest
#- drupal-ti script
after_script:
#- drupal-ti after_script
notifications:
  email: false
