language: php
sudo: required
php:
- 5.6

services:
- docker

cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/docker"

matrix:
  fast_finish: true
env:
  global:
  - PATH="$PATH:$HOME/.composer/vendor/bin"
  - ENCRYPTION_LABEL="4bbb05651be3"
  - COMMIT_AUTHOR_EMAIL="legovaer@me.com"

  matrix:
  - DRUPAL_TI_RUNNERS="simpletest"
mysql:
  database: drupal_travis_db
  username: root
  encoding: utf8
before_install:
  - ls -ls $HOME
  - ./scripts/downgrade-docker.sh
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - composer self-update
  - mkdir -p "$HOME/.composer/vendor/bin"
  - cd $HOME
  - git clone --branch 20160701_production https://git.drupal.org/project/drupalci_testbot.git
  - cd drupalci_testbot
  - composer install
  - ln -sf $HOME/drupalci_testbot/drupalci "$HOME/.composer/vendor/bin"
  - drupalci config:set DCI_CheckoutDir=$HOME/www/html/checkout
  - drupalci config:set DCI_RunScript=/var/www/html/core/scripts/run-tests.sh
  - drupalci config:set DCI_PHPVersion=5.5
  - drupalci config:set DCI_JobType=simpletest
  - drupalci config:set DCI_ComposerInstall=True
  - drupalci config:set DCI_CoreBranch=8.3.x
  - drupalci config:set DCI_Patch=add_readme_file-2809329-5.patch,modules/drupal_coverage_core
  - drupalci config:set DCI_AdditionalRepositories=git,git://git.drupal.org/project/scheduler.git,8.x-1.x,modules/scheduler,1
  - drupalci config:set DCI_Fetch=modules/scheduler
  - drupalci config:set DCI_TestItem=directory:modules/scheduler
  - drupalci config:set DCI_Color=True
  - drupalci config:set DCI_JunitXml=xml
  - drupalci config:set DCI_Concurrency=31
  - drupalci config:set DCI_CoreRepository=git://git.drupal.org/project/drupal.git
  - drupalci config:set DCI_DBVersion=mysql-5.5
  - drupalci docker-rm containers
  - if [[ ! -d $HOME/docker ]]; then drupalci init --no-interaction; fi
  - sudo chmod 0777 /var/www/html
  - sudo chmod 0777 /var/www/html/checkout
  - sudo chmod 0777 /tmp
  - mkdir -p $HOME/www/html/checkout

install:
#- drupal-ti install
before_script:
#- drupal-ti before_script
script:
  - drupalci run simpletest
  - sudo tail /var/lib/docker/containers/*/*.log
#- drupal-ti script
after_script:
#- drupal-ti after_script
notifications:
  email: false
before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
